#!/usr/bin/env python3
"""Generate docs/official-samples.md: every official sample in this
repository, and what this tool says about it.

Only the standard body's own published material -- IDTA's samples,
vendored at the upstream pin under CC BY 4.0 (`tools/vendor_template.py`
and THIRD_PARTY.md) -- and only this tool's verdict on each: the exit code
a caller would see with no flags, the rules that fire with their severity
and the requirement each reads from, the relayed metamodel findings
counted, and the version that judged. The templates are not samples and
are not listed; a template is set aside rather than judged, whatever
file it arrives in, and the page says so where a sample turns out to be
one.

The page is checked, not trusted: `--check` builds it again from a run and
fails if the committed page differs.

    python3 tools/gen_official_samples.py            # write
    python3 tools/gen_official_samples.py --check    # fail if the page and a run disagree
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import pathlib as _pathlib
import sys as _sys
import urllib.parse
from pathlib import Path

# The package, from wherever this script is, as the other tools find it.
_TOOLS_SRC = str(_pathlib.Path(__file__).resolve().parent.parent / "src")
if _TOOLS_SRC not in _sys.path:
    _sys.path.insert(0, _TOOLS_SRC)
_TOOLS = str(_pathlib.Path(__file__).resolve().parent)
if _TOOLS not in _sys.path:
    _sys.path.insert(0, _TOOLS)

import vendor_template  # noqa: E402
from aas_submodel_validate import __version__, runner  # noqa: E402
from aas_submodel_validate._terminal import survive  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "docs" / "official-samples.md"

#: Where this repository keeps IDTA's samples: the test corpus, and the
#: example the package ships for `smtv --example`. Everything else the
#: vendoring table names is a template.
_SAMPLE_TREES = ("tests/corpus/idta/", "src/aas_submodel_validate/data/example/")


def is_sample(rel: str) -> bool:
    return rel.startswith(_SAMPLE_TREES)


def _exit_code(report) -> int:
    """The code `smtv <file>` leaves by with no flags."""
    if not report.judged:
        return 2
    return 0 if report.ok else 1


def _verdict(report, code: int) -> str:
    if code == 2:
        return "exit 2 -- refused, not judged"
    summary = report.as_dict()["summary"]
    counts = "%d error(s), %d warning(s), %d info" % (
        summary["errors"], summary["warnings"], summary["info"])
    judged = "judged %d of %d submodel%s" % (
        report.submodels_judged, report.submodels_seen,
        "" if report.submodels_seen == 1 else "s")
    if report.submodels_specified:
        judged += ", %d set aside as a template" % report.submodels_specified
    return "exit %d -- %s; %s" % (code, counts, judged)


def _cell(text: str) -> str:
    return " ".join((text or "").split()).replace("|", "\\|")


def _section(rel: str, report) -> str:
    path = ROOT / rel
    source = vendor_template.FILES[rel]
    url = "https://github.com/%s/blob/%s/%s" % (
        vendor_template.REPO, vendor_template.COMMIT, urllib.parse.quote(source))
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    code = _exit_code(report)
    findings = [f for f in report.as_dict()["findings"] if f["kind"] != "meta"]
    relayed = sum(1 for f in report.as_dict()["findings"] if f["kind"] == "meta")
    lines = ["## `%s`" % rel, "",
             "- Published as [`%s`](%s), at upstream commit `%s`." % (
                 source, url, vendor_template.COMMIT[:12]),
             "- Licence: CC BY 4.0, © IDTA and contributors (THIRD_PARTY.md). sha256 `%s`." % digest,
             "- Verdict, version %s: %s." % (__version__, _verdict(report, code)),
             "- Metamodel findings relayed (not this project's rules): %d." % relayed,
             ""]
    if findings:
        grouped = collections.Counter((f["rule"], f["severity"], f["spec"]) for f in findings)
        lines += ["| Rule | Severity | Reads from | Findings |", "|---|---|---|---|"]
        for (rule, severity, spec), count in sorted(grouped.items()):
            lines.append("| %s | %s | %s | %d |" % (rule, severity, _cell(spec), count))
    else:
        lines.append("No rule of this project fires.")
    return "\n".join(lines) + "\n"


def render() -> str:
    samples = sorted(rel for rel in vendor_template.FILES if is_sample(rel))
    head = [
        "# Official samples, and what this tool says about each",
        "",
        "Every sample IDTA publishes that this repository vendors, with the verdict "
        "this version gives it. Generated by `tools/gen_official_samples.py` from the "
        "files and a run with no flags; `make check` and CI build the page again and "
        "fail when it and a run disagree. A sample is IDTA's own material, pinned by "
        "upstream commit and hash, and it is here with its defects: nothing is "
        "repaired, and a sample is not assumed to conform because it is official.",
        "",
        "| Sample | Verdict |",
        "|---|---|",
    ]
    rows, sections = [], []
    for rel in samples:
        report = runner.run(ROOT / rel)          # once per sample, for both
        rows.append("| `%s` | %s |" % (rel, _verdict(report, _exit_code(report))))
        sections.append(_section(rel, report))
    return "\n".join(head + rows) + "\n\n" + "\n".join(sections)


def main() -> int:
    survive()
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed page differs from a run")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not PAGE.exists() or PAGE.read_text("utf-8") != text:
            print("docs/official-samples.md is not what a run writes; "
                  "`python3 tools/gen_official_samples.py` writes it", file=_sys.stderr)
            return 1
        print("official samples page matches a run (%d samples)"
              % sum(1 for rel in vendor_template.FILES if is_sample(rel)))
        return 0
    PAGE.write_text(text, "utf-8")
    print("wrote docs/official-samples.md")
    return 0


if __name__ == "__main__":
    _sys.exit(main())
