# -*- coding: utf-8 -*-
"""Join the derived indexes and list where they disagree.

The same obligation is written down three times: once in the regulation, once in
the Commission's guidance table and in the consortium longlist that restate it,
and once in the submodel templates that carry it as data. This walks the four
indexes and lines those statements up.

Two joins, and they are not the same kind of thing:

  * By citation. The guidance and the longlist each name the provision a data
    point comes from. Those citations are normalised to one form and matched
    against the annex index. A citation is an assertion by the document that
    made it, so a citation that does not resolve against the consolidated text
    read here is reported, not repaired -- and reported as what it is: an
    observation about one text at one version, which a later amendment may
    change without making the observation wrong.
  * By name. The templates cite nothing. All that can be matched is the element
    name against the attribute name, after both are reduced to a bag of
    lowercase words. That is a weak join and it is labelled as one: only exact
    bag matches are recorded, and everything else is left in the unmatched lists
    where it can be looked at.

Nothing here decides who is right when two sources differ. It produces the list
of places where they do.

The markdown table it can write is generated, not maintained: every number in it
comes from this run. Nobody types a count into a document by hand -- a count
typed by hand is a count that stops being true the next time a source moves.

Usage:
    python3 tools/join_requirements.py --out requirements-join.json \
        --md requirements-join.md
"""

import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _common  # noqa: E402

DEFAULT_INDEXES = {
    "annex-xiii": "requirements-annex-xiii.json",
    "ec-datapoints": "requirements-ec-datapoints.json",
    "longlist": "requirements-longlist.json",
    "idta-smt": "requirements-idta.json",
}

ANNEX_XIII = re.compile(r"annex\s+xiii\s*,?\s*\(?\s*(\d)\s*\)?\s*\(?\s*([a-z])?\s*\)?", re.I)
ANNEX_VI_A = re.compile(r"annex\s+vi\s*(?:part\s*)?[,\s]*a\s*\(?\s*(\d+)\s*\)?", re.I)
ARTICLE = re.compile(r"art(?:icle)?\.?\s*(\d+)\s*\(\s*(\d+)\s*\)", re.I)

CAMEL = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")
NON_WORD = re.compile(r"[^a-z0-9]+")
# Words that say nothing about which attribute this is.
STOPWORDS = frozenset(
    "the a an of for to in on and or by is with as at from its their this that "
    "information data value values battery batteries".split()
)


def citations(text):
    """Every provision a piece of text names, in one canonical form."""
    found = []
    for block, letter in ANNEX_XIII.findall(text or ""):
        found.append("annex-xiii:%s.%s" % (block, letter) if letter else "annex-xiii:%s" % block)
    for point in ANNEX_VI_A.findall(text or ""):
        found.append("annex-vi-a:%s" % point)
    for article, paragraph in ARTICLE.findall(text or ""):
        found.append("article:%s.%s" % (article, paragraph))
    return sorted(set(found))


def words_of(text):
    spaced = CAMEL.sub(" ", text or "")
    tokens = [t for t in NON_WORD.sub(" ", spaced.lower()).split() if t]
    return frozenset(t for t in tokens if t not in STOPWORDS)


def load(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def render_markdown(doc):
    lines = []
    add = lines.append
    add("# Battery passport obligations: the same requirement, read four ways")
    add("")
    add("Generated by `tools/join_requirements.py`. Do not edit: every number below")
    add("comes from the indexes named in the table of sources, and re-running the")
    add("tool overwrites this file.")
    add("")
    add("## Sources this join was built from")
    add("")
    add("| index | records | file | sha256 | edition |")
    add("|---|---:|---|---|---|")
    for name, index in doc["indexes"].items():
        for i, p in enumerate(index["provenance"]):
            add("| %s | %s | `%s` | `%s` | %s |" % (
                name if i == 0 else "",
                index["records"] if i == 0 else "",
                p["file"], p["sha256"][:12], p.get("version", ""),
            ))
    add("")
    add("## What the join found")
    add("")
    add("**Every coverage figure here is a floor, not a measurement.** The templates")
    add("carry no citation of the law, so a template element can only be matched to an")
    add("attribute by name, and name matching misses more than it finds. Read these as")
    add("lower bounds until a citation-bearing bridge exists.")
    add("")
    add("| measure | count |")
    add("|---|---:|")
    for k, v in doc["counts"].items():
        add("| %s | %s |" % (k.replace("_", " "), v))
    add("")
    add("## Every point of the annex, and who restates it")
    add("")
    add("`through parent` means the point is a sub-item of a point that is cited,")
    add("and is not named on its own by either restatement.")
    add("")
    add("| annex point | access | required | guidance data points | longlist rows | |")
    add("|---|---|---|---|---|---|")
    for a in doc["annex_coverage"]:
        add("| `%s` | %s | %s | %s | %s | %s |" % (
            a["annex_point"], a["access"], a["mandatory"],
            ", ".join(x.split(":")[-1] for x in a["ec_datapoints"]) or "-",
            ", ".join(x.split(":")[-1] for x in a["longlist_rows"]) or "-",
            "through parent" if a["cited_only_through_its_parent"] else "",
        ))
    add("")
    add("## Where two restatements of the same provision disagree")
    add("")
    if not doc["readings_that_differ_by_citation"]:
        add("None.")
    else:
        add("| provision | reading | records |")
        add("|---|---|---|")
        for x in doc["readings_that_differ_by_citation"]:
            for reading, ids in sorted(x["readings"].items()):
                add("| `%s` | %s | %s |" % (x["citation"], reading, ", ".join(ids)))
    add("")
    add("## Where a template element and the attribute it matches disagree")
    add("")
    add("Matched on name alone -- the templates carry no citation -- so each row is")
    add("a candidate to be read, not a finding on its own.")
    add("")
    if not doc["readings_that_differ_by_name"]:
        add("None.")
    else:
        add("| template element | template says | restatement says |")
        add("|---|---|---|")
        for x in doc["readings_that_differ_by_name"]:
            template = [k for k in x["readings"] if k.startswith("template(")]
            others = [k for k in x["readings"] if not k.startswith("template(")]
            add("| `%s` | %s (%s) | %s |" % (
                x["element"].split(":", 1)[1],
                x["readings"][template[0]] if template else "?",
                template[0].strip("template()") if template else "?",
                "; ".join("%s: %s" % (o, x["readings"][o]) for o in others),
            ))
    add("")
    add("## Citations not resolved in the consolidated text that was read")
    add("")
    add("Read against **%s**. A citation listed here names a" % doc["consolidated_text"])
    add("provision that text does not contain. A later amendment may add it, which")
    add("would not make this line wrong: it is a statement about one text at one")
    add("version, not about whether the citing document is mistaken.")
    add("")
    if not doc["citations_without_a_matching_annex_point"]:
        add("None.")
    else:
        add("| citation | as written | cited by |")
        add("|---|---|---|")
        for x in doc["citations_without_a_matching_annex_point"]:
            add("| `%s` | %s | %s |" % (x["citation"], x["as_written"], x["cited_by"]))
    add("")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dir", default=".")
    ap.add_argument("--out", default="requirements-join.json")
    ap.add_argument("--md", default="", help="also write the join table as markdown")
    args = ap.parse_args(argv)

    indexes = {}
    for name, filename in DEFAULT_INDEXES.items():
        path = os.path.join(args.dir, filename)
        if not os.path.exists(path):
            raise SystemExit("missing index %r -- run the extractor first" % filename)
        indexes[name] = load(path)

    annex = indexes["annex-xiii"]["records"]
    guidance = indexes["ec-datapoints"]["records"]
    longlist = indexes["longlist"]["records"]
    elements = indexes["idta-smt"]["records"]

    annex_ids = {r["id"].split(":", 1)[1]: r for r in annex}
    annex_keys = {"annex-xiii:%s" % k for k in annex_ids}
    # A citation may name a whole block ("Annex XIII 3") or a point that has
    # sub-items ("Annex XIII 2 (c)"). Both are citations of everything beneath
    # them, so a prefix that opens a real point counts as naming that point.
    annex_prefixes = set()
    for key in annex_ids:
        parts = key.split(".")
        for i in range(1, len(parts)):
            annex_prefixes.add("annex-xiii:%s" % ".".join(parts[:i]))

    def points_named_by(citation):
        if citation in annex_keys:
            return [citation]
        if citation in annex_prefixes:
            return sorted(k for k in annex_keys if k.startswith(citation + "."))
        return []

    # -- join by citation ---------------------------------------------------
    cited = {}          # canonical citation -> {"ec": [...], "longlist": [...]}
    dangling = []       # citations that name a provision the annex does not have
    for source, records, field in (
        ("ec-datapoints", guidance, "legal_source"),
        ("longlist", longlist, "legal_reference"),
    ):
        for r in records:
            for key in citations(r.get(field, "")):
                cited.setdefault(key, {}).setdefault(source, []).append(r["id"])
                if not key.startswith("annex-xiii:"):
                    continue
                named = points_named_by(key)
                for point in named:
                    if point != key:
                        cited.setdefault(point, {}).setdefault(source, []).append(r["id"])
                if not named:
                    dangling.append(
                        {
                            "citation": key,
                            "cited_by": r["id"],
                            "as_written": _common.squeeze(r.get(field, ""))[:120],
                            "source": source,
                        }
                    )

    annex_coverage = []
    for key, record in sorted(annex_ids.items()):
        hits = cited.get("annex-xiii:%s" % key, {})
        parent = "annex-xiii:%s" % key.rsplit(".", 1)[0] if "." in key else ""
        parent_hits = cited.get(parent, {}) if parent else {}
        annex_coverage.append(
            {
                "annex_point": "annex-xiii:%s" % key,
                "text": record["text"][:110],
                "access": record["access"],
                "mandatory": record["mandatory"],
                "ec_datapoints": sorted(set(hits.get("ec-datapoints", []))),
                "longlist_rows": sorted(set(hits.get("longlist", []))),
                "cited_only_through_its_parent": bool(
                    not hits and (parent_hits.get("ec-datapoints") or parent_hits.get("longlist"))
                ),
            }
        )

    # -- join by name -------------------------------------------------------
    def bag_index(records):
        out = {}
        for r in records:
            bag = words_of(r["text"])
            if bag:
                out.setdefault(bag, []).append(r["id"])
        return out

    guidance_bags = bag_index(guidance)
    longlist_bags = bag_index(longlist)

    name_matches, unmatched_elements = [], []
    for element in elements:
        bag = words_of(element.get("id_short", "") or element["text"])
        hit_guidance = guidance_bags.get(bag, [])
        hit_longlist = longlist_bags.get(bag, [])
        if hit_guidance or hit_longlist:
            name_matches.append(
                {
                    "element": element["id"],
                    "template": element.get("template", ""),
                    "cardinality": element.get("cardinality", ""),
                    "mandatory": element["mandatory"],
                    "ec_datapoints": hit_guidance,
                    "longlist_rows": hit_longlist,
                }
            )
        else:
            unmatched_elements.append(element["id"])

    matched_guidance = {i for m in name_matches for i in m["ec_datapoints"]}
    matched_longlist = {i for m in name_matches for i in m["longlist_rows"]}

    # -- where the three readings differ ------------------------------------
    by_id = {r["id"]: r for r in guidance + longlist}
    disagreements = []
    for match in name_matches:
        readings = {"template(%s)" % match["template"]: match["mandatory"]}
        for other in match["ec_datapoints"] + match["longlist_rows"]:
            readings[other] = by_id[other]["mandatory"]
        if len(set(readings.values())) > 1:
            disagreements.append({"element": match["element"], "readings": readings})

    citation_disagreements = []
    for key, hits in sorted(cited.items()):
        if "ec-datapoints" not in hits or "longlist" not in hits:
            continue
        readings = {}
        for i in sorted(set(hits["ec-datapoints"] + hits["longlist"])):
            readings.setdefault(by_id[i]["mandatory"], []).append(i)
        if len(readings) > 1:
            citation_disagreements.append({"citation": key, "readings": readings})

    doc = {
        "join": "battery passport obligations, four indexes",
        "consolidated_text": "CELEX 02023R1542-20250731",
        "indexes": {
            name: {
                "records": index["counts"]["records"],
                "provenance": [
                    {"file": p["file"], "sha256": p["sha256"], "version": p.get("version", "")}
                    for p in index["provenance"]
                ],
            }
            for name, index in indexes.items()
        },
        "counts": {
            "annex_points": len(annex_ids),
            "annex_points_with_a_guidance_data_point": sum(
                1 for a in annex_coverage if a["ec_datapoints"]
            ),
            "annex_points_with_a_longlist_row": sum(
                1 for a in annex_coverage if a["longlist_rows"]
            ),
            "annex_points_with_neither": sum(
                1 for a in annex_coverage if not a["ec_datapoints"] and not a["longlist_rows"]
            ),
            "annex_points_named_only_through_their_parent": sum(
                1 for a in annex_coverage if a["cited_only_through_its_parent"]
            ),
            "citations_unresolved_in_consolidated_text": len(dangling),
            "template_elements": len(elements),
            "template_elements_matched_by_name": len(name_matches),
            "template_elements_matched_by_nothing": len(unmatched_elements),
            "guidance_data_points_matched_by_name": len(matched_guidance),
            "guidance_data_points_unmatched": len(guidance) - len(matched_guidance),
            "longlist_rows_matched_by_name": len(matched_longlist),
            "longlist_rows_unmatched": len(longlist) - len(matched_longlist),
            "name_matches_where_the_readings_differ": len(disagreements),
            "citations_where_the_readings_differ": len(citation_disagreements),
        },
        "coverage_is_a_floor": (
            "The templates carry no citation of the law, so a template element can "
            "only be matched to an attribute by name. Name matching is weak: it "
            "misses every element whose label differs from the prose attribute "
            "name, and it cannot match a nested element to an attribute at all. "
            "Every coverage figure below is therefore a lower bound on what is "
            "actually covered, not a measurement of it, and must be reported as "
            "such until a citation-bearing bridge exists."
        ),
        "annex_coverage": annex_coverage,
        "citations_without_a_matching_annex_point": dangling,
        "name_matches": name_matches,
        "template_elements_matched_by_nothing": unmatched_elements,
        "readings_that_differ_by_name": disagreements,
        "readings_that_differ_by_citation": citation_disagreements,
    }

    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, ensure_ascii=False, indent=1)
        fh.write("\n")
    if args.md:
        with open(args.md, "w", encoding="utf-8") as fh:
            fh.write(render_markdown(doc))
        print("wrote %s" % args.md)
    print("wrote %s" % args.out)
    for k, v in doc["counts"].items():
        print("  %-52s %s" % (k, v))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
