"""Join the derived indexes and list where they disagree.

The same obligation is written down three times: once in the regulation, once in
the Commission's guidance table and in the consortium longlist that restate it,
and once in the submodel templates that carry it as data. This walks the four
indexes and lines those statements up.

Two joins, and they are not the same kind of thing:

  * By citation. The guidance and the longlist each name the provision a data
    point comes from. Those citations are normalised to one form and matched
    against the annex index. A citation is an assertion by the document that
    made it, so a citation that does not resolve against the consolidated text
    read here is reported, not repaired -- and reported as what it is: an
    observation about one text at one version, which a later amendment may
    change without making the observation wrong.
  * By name. The templates cite nothing. All that can be matched is the element
    name against the attribute name, after both are reduced to a bag of
    lowercase words. That is a weak join and it is labelled as one: only exact
    bag matches are recorded, and everything else is left in the unmatched lists
    where it can be looked at.

Nothing here decides who is right when two sources differ. It produces the list
of places where they do.

The markdown table it can write is generated, not maintained: every number in it
comes from this run. Nobody types a count into a document by hand -- a count
typed by hand is a count that stops being true the next time a source moves.

Usage:
    python3 tools/join_requirements.py --out requirements-join.json \
        --md requirements-join.md
"""

import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _common  # noqa: E402

DEFAULT_INDEXES = {
    "annex-xiii": "requirements-annex-xiii.json",
    "ec-datapoints": "requirements-ec-datapoints.json",
    "longlist": "requirements-longlist.json",
    "idta-smt": "requirements-idta.json",
}

ANNEX_XIII = re.compile(r"annex\s+xiii\s*,?\s*\(?\s*(\d)\s*\)?\s*\(?\s*([a-z])?\s*\)?", re.I)
ANNEX_VI_A = re.compile(r"annex\s+vi\s*(?:part\s*)?[,\s]*a\s*\(?\s*(\d+)\s*\)?", re.I)
ARTICLE = re.compile(r"art(?:icle)?\.?\s*(\d+)\s*\(\s*(\d+)\s*\)", re.I)

CAMEL = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")
NON_WORD = re.compile(r"[^a-z0-9]+")
# Words that say nothing about which attribute this is.
STOPWORDS = frozenset(
    # ruff's SIM905 wants a list literal here. Twenty-six one-word
    # strings, one per line, is harder to read and harder to diff than
    # the sentence it would replace, and this list is read far more often
    # than it is changed -- `value` is in it, and `value` is why four
    # matched elements collapse onto their own parent.
    "the a an of for to in on and or by is with as at from its their this that "  # noqa: SIM905
    "information data value values battery batteries".split()
)


def citations(text):
    """Every provision a piece of text names, in one canonical form."""
    found = []
    for block, letter in ANNEX_XIII.findall(text or ""):
        found.append("annex-xiii:%s.%s" % (block, letter) if letter else "annex-xiii:%s" % block)
    for point in ANNEX_VI_A.findall(text or ""):
        found.append("annex-vi-a:%s" % point)
    for article, paragraph in ARTICLE.findall(text or ""):
        found.append("article:%s.%s" % (article, paragraph))
    return sorted(set(found))


def words_of(text):
    spaced = CAMEL.sub(" ", text or "")
    tokens = [t for t in NON_WORD.sub(" ", spaced.lower()).split() if t]
    return frozenset(t for t in tokens if t not in STOPWORDS)


def load(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def render_markdown(doc):
    lines = []
    add = lines.append
    add("# Battery passport obligations: the same requirement, read four ways")
    add("")
    add("Generated by `tools/join_requirements.py`. Do not edit: every number below")
    add("comes from the indexes named in the table of sources, and re-running the")
    add("tool overwrites this file.")
    add("")
    add("## Sources this join was built from")
    add("")
    add("| index | records | file | sha256 | edition |")
    add("|---|---:|---|---|---|")
    for name, index in doc["indexes"].items():
        for i, p in enumerate(index["provenance"]):
            add("| %s | %s | `%s` | `%s` | %s |" % (
                name if i == 0 else "",
                index["records"] if i == 0 else "",
                p["file"], p["sha256"][:12], p.get("version", ""),
            ))
    add("")
    add("## What the join found")
    add("")
    add("**Every coverage figure here is a floor, not a measurement.** The templates")
    add("carry no citation of the law, so a template element can only be matched to an")
    add("attribute by name, and name matching misses more than it finds. Read these as")
    add("lower bounds until a citation-bearing bridge exists.")
    add("")
    add("| measure | count |")
    add("|---|---:|")
    for k, v in doc["counts"].items():
        add("| %s | %s |" % (k.replace("_", " "), v))
    add("")
    add("## Every point of the annex, and who restates it")
    add("")
    add("`through parent` means the point is a sub-item of a point that is cited,")
    add("and is not named on its own by either restatement. That set is a subset of")
    add("`annex points with neither` above -- a point reached only through its parent")
    add("has nothing of its own -- so the two counts cannot disagree in the direction")
    add("a reader expects, and reading 6 and 6 as twelve points would be wrong: they")
    add("are the same six. Their being equal is the fact worth having, and it is that")
    add("every point no restatement names has a parent that is named.")
    add("")
    add("The last column is not coverage. A citation of a whole block -- `Annex XIII")
    add("(1)`, which has nineteen lettered points beneath it -- reaches every point in")
    add("the block without naming any of them, so the record is shown against each and")
    add("counted against none. Two longlist rows about expected lifetime cite that")
    add("block in passing; reading them as a restatement of all nineteen would put")
    add("nineteen obligations above the floor on the strength of one citation.")
    add("")
    add("| annex point | access | required | guidance data points | longlist rows |"
        " reached without being named | |")
    add("|---|---|---|---|---|---|---|")
    for a in doc["annex_coverage"]:
        broader = a["reached_by_a_broader_citation"]
        add("| `%s` | %s | %s | %s | %s | %s | %s |" % (
            a["annex_point"], a["access"], a["mandatory"],
            ", ".join(x.split(":")[-1] for x in a["ec_datapoints"]) or "-",
            ", ".join(x.split(":")[-1] for x in a["longlist_rows"]) or "-",
            ", ".join(x.split(":")[-1]
                      for x in broader["ec_datapoints"] + broader["longlist_rows"]) or "-",
            "through parent" if a["cited_only_through_its_parent"] else "",
        ))
    add("")
    add("## Where two restatements of the same provision disagree")
    add("")
    if not doc["readings_that_differ_by_citation"]:
        add("None.")
    else:
        add("| provision | reading | records |")
        add("|---|---|---|")
        for x in doc["readings_that_differ_by_citation"]:
            for reading, ids in sorted(x["readings"].items()):
                add("| `%s` | %s | %s |" % (x["citation"], reading, ", ".join(ids)))
    add("")
    add("## Where a template element and the attribute it matches disagree")
    add("")
    add("Matched on name alone -- the templates carry no citation -- so each row is")
    add("a candidate to be read, not a finding on its own.")
    add("")
    if not doc["readings_that_differ_by_name"]:
        add("None.")
    else:
        add("| template element | template says | restatement says |")
        add("|---|---|---|")
        for x in doc["readings_that_differ_by_name"]:
            template = [k for k in x["readings"] if k.startswith("template(")]
            others = [k for k in x["readings"] if not k.startswith("template(")]
            add("| `%s` | %s (%s) | %s |" % (
                x["element"].split(":", 1)[1],
                x["readings"][template[0]] if template else "?",
                template[0][len("template("):-1] if template else "?",
                "; ".join("%s: %s" % (o, x["readings"][o]) for o in others),
            ))
    add("")
    add("## Citations not resolved in the consolidated text that was read")
    add("")
    add("Read against **%s**. A citation listed here names a" % doc["consolidated_text"])
    add("provision that text does not contain. A later amendment may add it, which")
    add("would not make this line wrong: it is a statement about one text at one")
    add("version, not about whether the citing document is mistaken.")
    add("")
    if not doc["citations_without_a_matching_annex_point"]:
        add("None.")
    else:
        add("| citation | as written | cited by |")
        add("|---|---|---|")
        for x in doc["citations_without_a_matching_annex_point"]:
            add("| `%s` | %s | %s |" % (x["citation"], x["as_written"], x["cited_by"]))
    add("")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dir", default=".")
    ap.add_argument("--out", default="requirements-join.json")
    ap.add_argument("--md", default="", help="also write the join table as markdown")
    args = ap.parse_args(argv)

    indexes = {}
    for name, filename in DEFAULT_INDEXES.items():
        path = os.path.join(args.dir, filename)
        if not os.path.exists(path):
            raise SystemExit("missing index %r -- run the extractor first" % filename)
        indexes[name] = load(path)

    annex = indexes["annex-xiii"]["records"]
    guidance = indexes["ec-datapoints"]["records"]
    longlist = indexes["longlist"]["records"]
    elements = indexes["idta-smt"]["records"]

    annex_ids = {r["id"].split(":", 1)[1]: r for r in annex}
    annex_keys = {"annex-xiii:%s" % k for k in annex_ids}
    # A citation may name a whole block ("Annex XIII 3") or a point that has
    # sub-items ("Annex XIII 2 (c)"). Both are citations of everything beneath
    # them, so a prefix that opens a real point counts as naming that point.
    annex_prefixes = set()
    for key in annex_ids:
        parts = key.split(".")
        for i in range(1, len(parts)):
            annex_prefixes.add("annex-xiii:%s" % ".".join(parts[:i]))

    def points_named_by(citation):
        """The points a citation reaches, and whether it *names* them.

        A block with one point beneath it has no content of its own:
        `Annex XIII 3` is that single sentence, and the index gives it a
        sub-item id only because the source left it unlettered. Citing
        the block names that point, with no choice made.

        A block with nineteen points beneath it is a different animal.
        Naming it picks out none of them, and crediting all nineteen
        turns one citation into nineteen statements the source never
        made -- two longlist rows about expected lifetime name the whole
        of point 1 in passing and say nothing whatever about responsible
        sourcing at 1(d) or marking at 1(q). Those reach the points
        beneath, and are reported as reaching them, but they do not name
        them and are not counted as coverage: every figure here is
        published as a floor, and a credit nobody made is the one kind
        of error a floor cannot absorb.
        """
        if citation in annex_keys:
            return [citation], True
        if citation in annex_prefixes:
            beneath = sorted(k for k in annex_keys if k.startswith(citation + "."))
            return beneath, len(beneath) == 1
        return [], False

    # -- join by citation ---------------------------------------------------
    cited = {}          # canonical citation -> {"ec": [...], "longlist": [...]}
    contained = {}      # same, for points a broader citation reaches but does not name
    dangling = []       # citations that name a provision the annex does not have
    # How much of the citing was looked at. Only Annex XIII citations can
    # be resolved here, because nothing in this directory indexes Annex VI
    # or the articles of the regulation -- so `dangling` is a count of
    # what failed among the ones that were checked, and its name has
    # always sounded like a count over all of them.
    checked = unresolvable = 0
    for source, records, field in (
        ("ec-datapoints", guidance, "legal_source"),
        ("longlist", longlist, "legal_reference"),
    ):
        for r in records:
            for key in citations(r.get(field, "")):
                cited.setdefault(key, {}).setdefault(source, []).append(r["id"])
                if not key.startswith("annex-xiii:"):
                    unresolvable += 1
                    continue
                checked += 1
                named, names_them = points_named_by(key)
                for point in named:
                    if point != key:
                        reached = cited if names_them else contained
                        reached.setdefault(point, {}).setdefault(source, []).append(r["id"])
                if not named:
                    dangling.append(
                        {
                            "citation": key,
                            "cited_by": r["id"],
                            "as_written": _common.squeeze(r.get(field, ""))[:120],
                            "source": source,
                        }
                    )

    annex_coverage = []
    for key, record in sorted(annex_ids.items()):
        hits = cited.get("annex-xiii:%s" % key, {})
        broader = contained.get("annex-xiii:%s" % key, {})
        parent = "annex-xiii:%s" % key.rsplit(".", 1)[0] if "." in key else ""
        parent_hits = cited.get(parent, {}) if parent else {}
        annex_coverage.append(
            {
                "annex_point": "annex-xiii:%s" % key,
                "text": record["text"][:110],
                "access": record["access"],
                "mandatory": record["mandatory"],
                "ec_datapoints": sorted(set(hits.get("ec-datapoints", []))),
                "longlist_rows": sorted(set(hits.get("longlist", []))),
                "reached_by_a_broader_citation": {
                    "ec_datapoints": sorted(set(broader.get("ec-datapoints", []))),
                    "longlist_rows": sorted(set(broader.get("longlist", []))),
                },
                "cited_only_through_its_parent": bool(
                    not hits and (parent_hits.get("ec-datapoints") or parent_hits.get("longlist"))
                ),
            }
        )

    # -- join by name -------------------------------------------------------
    def bag_index(records):
        out = {}
        for r in records:
            bag = words_of(r["text"])
            if bag:
                out.setdefault(bag, []).append(r["id"])
        return out

    guidance_bags = bag_index(guidance)
    longlist_bags = bag_index(longlist)

    name_matches, unmatched_elements, matched_bags = [], [], set()
    for element in elements:
        bag = words_of(element.get("id_short", "") or element["text"])
        hit_guidance = guidance_bags.get(bag, [])
        hit_longlist = longlist_bags.get(bag, [])
        if hit_guidance or hit_longlist:
            matched_bags.add(bag)
            name_matches.append(
                {
                    "element": element["id"],
                    "template": element.get("template", ""),
                    "cardinality": element.get("cardinality", ""),
                    "mandatory": element["mandatory"],
                    "ec_datapoints": hit_guidance,
                    "longlist_rows": hit_longlist,
                }
            )
        else:
            unmatched_elements.append(element["id"])

    matched_guidance = {i for m in name_matches for i in m["ec_datapoints"]}
    matched_longlist = {i for m in name_matches for i in m["longlist_rows"]}

    # -- where the three readings differ ------------------------------------
    by_id = {r["id"]: r for r in guidance + longlist}
    disagreements = []
    for match in name_matches:
        # The name of this key is parsed back out in `render_markdown`,
        # which is a small trap: it was read with `.strip("template()")`,
        # which strips *characters* from both ends and not the wrapper.
        # Every template here is `IDTA 02035-N`, which begins and ends
        # outside that set, so it gave the right answer for the wrong
        # reason; a template whose name began with any of `t e m p l a`
        # in lower case would have come out shortened.
        readings = {"template(%s)" % match["template"]: match["mandatory"]}
        for other in match["ec_datapoints"] + match["longlist_rows"]:
            readings[other] = by_id[other]["mandatory"]
        if len(set(readings.values())) > 1:
            disagreements.append({"element": match["element"], "readings": readings})

    citation_disagreements = []
    for key, hits in sorted(cited.items()):
        if "ec-datapoints" not in hits or "longlist" not in hits:
            continue
        readings = {}
        for i in sorted(set(hits["ec-datapoints"] + hits["longlist"])):
            readings.setdefault(by_id[i]["mandatory"], []).append(i)
        if len(readings) > 1:
            citation_disagreements.append({"citation": key, "readings": readings})

    doc = {
        "join": "battery passport obligations, four indexes",
        "consolidated_text": "CELEX 02023R1542-20250731",
        "indexes": {
            name: {
                "records": index["counts"]["records"],
                "provenance": [
                    {"file": p["file"], "sha256": p["sha256"], "version": p.get("version", "")}
                    for p in index["provenance"]
                ],
            }
            for name, index in indexes.items()
        },
        "counts": {
            "annex_points": len(annex_ids),
            "annex_points_with_a_guidance_data_point": sum(
                1 for a in annex_coverage if a["ec_datapoints"]
            ),
            "annex_points_with_a_longlist_row": sum(
                1 for a in annex_coverage if a["longlist_rows"]
            ),
            "annex_points_with_neither": sum(
                1 for a in annex_coverage if not a["ec_datapoints"] and not a["longlist_rows"]
            ),
            "annex_points_named_only_through_their_parent": sum(
                1 for a in annex_coverage if a["cited_only_through_its_parent"]
            ),
            # Not coverage. Published beside the coverage figures because
            # the difference between the two is the whole argument for
            # calling them floors, and a reader who cannot see the gap
            # cannot check the claim.
            "annex_points_a_broader_citation_reaches_without_naming": sum(
                1 for a in annex_coverage
                if a["reached_by_a_broader_citation"]["ec_datapoints"]
                or a["reached_by_a_broader_citation"]["longlist_rows"]
            ),
            "citations_unresolved_in_consolidated_text": len(dangling),
            "citations_checked_against_the_annex": checked,
            "citations_no_index_here_can_resolve": unresolvable,
            "template_elements": len(elements),
            "template_elements_matched_by_name": len(name_matches),
            # Read as coverage, the line above says more than it means.
            # The forty-two elements carry thirty-seven distinct names
            # between them: four are the value child of another matched
            # element -- `RemainingCapacity` and `RemainingCapacityValue`
            # reduce to one bag, because `value` says nothing about which
            # attribute an element is -- and a fifth pair is two elements
            # in two templates on one attribute. Both numbers are
            # published so the gap belongs to the reader rather than to
            # whoever finds it first.
            "distinct_attribute_names_those_elements_reach": len(matched_bags),
            "template_elements_matched_by_nothing": len(unmatched_elements),
            "guidance_data_points_matched_by_name": len(matched_guidance),
            "guidance_data_points_unmatched": len(guidance) - len(matched_guidance),
            "longlist_rows_matched_by_name": len(matched_longlist),
            "longlist_rows_unmatched": len(longlist) - len(matched_longlist),
            "name_matches_where_the_readings_differ": len(disagreements),
            "citations_where_the_readings_differ": len(citation_disagreements),
        },
        "coverage_is_a_floor": (
            "The templates carry no citation of the law, so a template element can "
            "only be matched to an attribute by name. Name matching is weak: it "
            "misses every element whose label differs from the prose attribute "
            "name, and it cannot match a nested element to an attribute at all. "
            "Every coverage figure below is therefore a lower bound on what is "
            "actually covered, not a measurement of it, and must be reported as "
            "such until a citation-bearing bridge exists."
        ),
        "annex_coverage": annex_coverage,
        "citations_without_a_matching_annex_point": dangling,
        "name_matches": name_matches,
        "template_elements_matched_by_nothing": unmatched_elements,
        "readings_that_differ_by_name": disagreements,
        "readings_that_differ_by_citation": citation_disagreements,
    }

    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, ensure_ascii=False, indent=1)
        fh.write("\n")
    if args.md:
        with open(args.md, "w", encoding="utf-8") as fh:
            fh.write(render_markdown(doc))
        print("wrote %s" % args.md)
    print("wrote %s" % args.out)
    for k, v in doc["counts"].items():
        print("  %-52s %s" % (k, v))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
